/**
 * Automation idea: config-driven suggestion for the chat.
 * Agent interprets base_prompt dynamically; no per-idea logic.
 */
export type AutomationIdea = {
  id: string;
  title: string;
  description: string;
  base_prompt: string;
  required_integrations: string[];
  optional_integrations: string[];
};

/** Sample automation ideas. Use same integration ids as in apps.ts (gmail, linear, slack, zoom, stripe, etc.). */
export const AUTOMATION_IDEAS: AutomationIdea[] = [
  {
    id: "summarize_inbox",
    title: "Summarize my inbox",
    description: "Get a brief summary of unread emails",
    base_prompt: "Summarize my unread emails and list the most important ones with senders and subjects.",
    required_integrations: ["gmail"],
    optional_integrations: [],
  },
  {
    id: "create_linear_issue",
    title: "Create a Linear issue",
    description: "Turn a short description into a Linear issue",
    base_prompt: "Create a Linear issue from this: [describe the issue]. Use the default team and set a sensible title and description.",
    required_integrations: ["linear"],
    optional_integrations: ["slack"],
  },
  {
    id: "schedule_zoom",
    title: "Schedule a Zoom meeting",
    description: "Create a Zoom meeting and optionally invite via Slack",
    base_prompt: "Schedule a Zoom meeting for [time/topic]. Create the meeting and share the link.",
    required_integrations: ["zoom"],
    optional_integrations: ["slack", "calendar"],
  },
  {
    id: "stripe_overview",
    title: "Stripe overview",
    description: "See recent customers and revenue",
    base_prompt: "Give me a short overview of my Stripe account: recent customers, revenue this month, and any failed payments.",
    required_integrations: ["stripe"],
    optional_integrations: [],
  },
  {
    id: "send_email",
    title: "Send an email",
    description: "Draft and send an email to a recipient",
    base_prompt: "Send an email to [recipient] with subject [subject] and body [your message].",
    required_integrations: ["gmail"],
    optional_integrations: [],
  },
  {
    id: "list_calendar_events",
    title: "List my calendar events",
    description: "See upcoming events for today or this week",
    base_prompt: "List my calendar events for today and the next 7 days.",
    required_integrations: ["calendar"],
    optional_integrations: [],
  },
  {
    id: "create_calendar_event",
    title: "Create a calendar event",
    description: "Add a new event to your calendar",
    base_prompt: "Create a calendar event: [title] on [date/time] with [optional details].",
    required_integrations: ["calendar"],
    optional_integrations: [],
  },
  {
    id: "list_slack_channels",
    title: "List Slack channels",
    description: "See all channels you're in",
    base_prompt: "List all Slack channels I'm a member of.",
    required_integrations: ["slack"],
    optional_integrations: [],
  },
  {
    id: "post_to_slack",
    title: "Post to Slack",
    description: "Send a message to a Slack channel",
    base_prompt: "Post this message to Slack channel [channel name]: [your message].",
    required_integrations: ["slack"],
    optional_integrations: [],
  },
  {
    id: "list_github_issues",
    title: "List GitHub issues",
    description: "See open issues for a repo",
    base_prompt: "List open issues in my GitHub repository [repo name].",
    required_integrations: ["github"],
    optional_integrations: [],
  },
  {
    id: "create_github_issue",
    title: "Create a GitHub issue",
    description: "Open a new issue in a repo",
    base_prompt: "Create a GitHub issue in [repo]: title [title], body [description].",
    required_integrations: ["github"],
    optional_integrations: [],
  },
  {
    id: "search_notion",
    title: "Search Notion",
    description: "Find pages and databases in Notion",
    base_prompt: "Search Notion for pages and databases matching [query].",
    required_integrations: ["notion"],
    optional_integrations: [],
  },
  {
    id: "list_drive_files",
    title: "List Google Drive files",
    description: "See files in a Drive folder",
    base_prompt: "List files in my Google Drive root (or folder [name]).",
    required_integrations: ["drive"],
    optional_integrations: [],
  },
  {
    id: "read_google_sheet",
    title: "Read a Google Sheet",
    description: "Get data from a spreadsheet",
    base_prompt: "Read and summarize the data from my Google Sheet [name or URL].",
    required_integrations: ["sheets"],
    optional_integrations: [],
  },
  {
    id: "find_unread_important",
    title: "Find important unread emails",
    description: "Prioritize emails from key senders",
    base_prompt: "Find my most important unread emails (e.g. from work, invoices, or key contacts) and list them with senders and subjects.",
    required_integrations: ["gmail"],
    optional_integrations: [],
  },
  {
    id: "archive_old_emails",
    title: "Archive old read emails",
    description: "Clean up inbox by archiving",
    base_prompt: "Archive read emails older than 30 days from my inbox.",
    required_integrations: ["gmail"],
    optional_integrations: [],
  },
  {
    id: "linear_board_status",
    title: "Linear board status",
    description: "See issues by status",
    base_prompt: "Show me the status of Linear issues: what's in progress, blocked, and done this week.",
    required_integrations: ["linear"],
    optional_integrations: [],
  },
  {
    id: "jira_sprint_report",
    title: "Jira sprint report",
    description: "Summarize current sprint",
    base_prompt: "Give me a brief report on the current Jira sprint: completed, in progress, and blocked issues.",
    required_integrations: ["jira"],
    optional_integrations: [],
  },
  {
    id: "trello_board_summary",
    title: "Trello board summary",
    description: "Overview of a Trello board",
    base_prompt: "Summarize my Trello board [board name]: lists and key cards.",
    required_integrations: ["trello"],
    optional_integrations: [],
  },
  {
    id: "asana_tasks_today",
    title: "Asana tasks for today",
    description: "List today's tasks",
    base_prompt: "List my Asana tasks due today.",
    required_integrations: ["asana"],
    optional_integrations: [],
  },
  {
    id: "stripe_failed_payments",
    title: "Stripe failed payments",
    description: "See failed charges",
    base_prompt: "List failed payments in Stripe from the last 7 days and suggest follow-up actions.",
    required_integrations: ["stripe"],
    optional_integrations: [],
  },
  {
    id: "zendesk_open_tickets",
    title: "Zendesk open tickets",
    description: "See unsolved support tickets",
    base_prompt: "List open Zendesk support tickets, sorted by priority.",
    required_integrations: ["zendesk"],
    optional_integrations: [],
  },
  {
    id: "airtable_list_records",
    title: "Airtable records",
    description: "List records from a base",
    base_prompt: "List records from my Airtable base [base name], table [table name].",
    required_integrations: ["airtable"],
    optional_integrations: [],
  },
  {
    id: "youtube_search",
    title: "Search YouTube",
    description: "Find videos by topic",
    base_prompt: "Search YouTube for videos about [topic] and list the top 5 results.",
    required_integrations: ["youtube"],
    optional_integrations: [],
  },
  {
    id: "figma_list_files",
    title: "List Figma files",
    description: "See design files",
    base_prompt: "List my Figma files and projects.",
    required_integrations: ["figma"],
    optional_integrations: [],
  },
  {
    id: "dropbox_list_folders",
    title: "List Dropbox folders",
    description: "See folders in Dropbox",
    base_prompt: "List folders in my Dropbox root.",
    required_integrations: ["dropbox"],
    optional_integrations: [],
  },
  {
    id: "post_bluesky",
    title: "Post to Bluesky",
    description: "Share a post on Bluesky",
    base_prompt: "Post to Bluesky: [your message].",
    required_integrations: ["bluesky"],
    optional_integrations: [],
  },
  {
    id: "post_twitter",
    title: "Post a tweet",
    description: "Share on X (Twitter)",
    base_prompt: "Post a tweet: [your message].",
    required_integrations: ["twitter"],
    optional_integrations: [],
  },
  {
    id: "outlook_unread",
    title: "Outlook unread emails",
    description: "List unread in Outlook",
    base_prompt: "List my unread Outlook emails with senders and subjects.",
    required_integrations: ["microsoft"],
    optional_integrations: [],
  },
  {
    id: "create_notion_page",
    title: "Create Notion page",
    description: "Add a new page",
    base_prompt: "Create a new Notion page titled [title] with content [description].",
    required_integrations: ["notion"],
    optional_integrations: [],
  },
  {
    id: "google_docs_summary",
    title: "Summarize a Google Doc",
    description: "Get a summary of a document",
    base_prompt: "Summarize the Google Doc [name or URL].",
    required_integrations: ["docs"],
    optional_integrations: [],
  },
  {
    id: "github_pr_list",
    title: "List GitHub PRs",
    description: "See open pull requests",
    base_prompt: "List open pull requests in [repo].",
    required_integrations: ["github"],
    optional_integrations: [],
  },
  {
    id: "slack_unread",
    title: "Slack unread messages",
    description: "Catch up on unread",
    base_prompt: "Summarize my unread Slack messages across channels.",
    required_integrations: ["slack"],
    optional_integrations: [],
  },
  {
    id: "zoom_upcoming",
    title: "Upcoming Zoom meetings",
    description: "See scheduled meetings",
    base_prompt: "List my upcoming Zoom meetings for the next 7 days.",
    required_integrations: ["zoom"],
    optional_integrations: [],
  },
  {
    id: "calendar_busy_times",
    title: "Find free slots",
    description: "When am I free?",
    base_prompt: "Find my free time slots tomorrow (or [date]) for a [duration]-minute meeting.",
    required_integrations: ["calendar"],
    optional_integrations: [],
  },
  {
    id: "gmail_search",
    title: "Search Gmail",
    description: "Find emails by criteria",
    base_prompt: "Search my Gmail for [query, e.g. from:sender, has:attachment, is:unread] and list the results.",
    required_integrations: ["gmail"],
    optional_integrations: [],
  },
  {
    id: "reply_to_email",
    title: "Reply to an email",
    description: "Draft a reply",
    base_prompt: "Reply to the email [subject or ID] with: [your reply].",
    required_integrations: ["gmail"],
    optional_integrations: [],
  },
  {
    id: "add_google_contact",
    title: "Add Google Contact",
    description: "Create a new contact",
    base_prompt: "Add a new Google Contact: name [name], email [email], phone [optional].",
    required_integrations: ["contacts"],
    optional_integrations: [],
  },
  {
    id: "drive_upload",
    title: "Upload to Drive",
    description: "Upload a file to Google Drive",
    base_prompt: "Upload the file [path or URL] to my Google Drive folder [folder name].",
    required_integrations: ["drive"],
    optional_integrations: [],
  },
  {
    id: "sheets_append_row",
    title: "Add row to Sheet",
    description: "Append data to a spreadsheet",
    base_prompt: "Append a row to my Google Sheet [name] with: [column values].",
    required_integrations: ["sheets"],
    optional_integrations: [],
  },
  {
    id: "linear_my_issues",
    title: "My Linear issues",
    description: "Issues assigned to me",
    base_prompt: "List Linear issues assigned to me, grouped by status.",
    required_integrations: ["linear"],
    optional_integrations: [],
  },
  {
    id: "stripe_customers",
    title: "Stripe customers list",
    description: "Recent customers",
    base_prompt: "List my most recent Stripe customers with email and subscription status.",
    required_integrations: ["stripe"],
    optional_integrations: [],
  },
  {
    id: "slack_create_channel",
    title: "Create Slack channel",
    description: "Start a new channel",
    base_prompt: "Create a new Slack channel named [name] with topic [topic].",
    required_integrations: ["slack"],
    optional_integrations: [],
  },
  {
    id: "notion_database_query",
    title: "Query Notion database",
    description: "Filter and sort database",
    base_prompt: "Query my Notion database [name] with filter [criteria] and return the top 10 results.",
    required_integrations: ["notion"],
    optional_integrations: [],
  },
  {
    id: "meeting_notes",
    title: "Draft meeting notes",
    description: "Create notes from a meeting",
    base_prompt: "Create a Google Doc with meeting notes for [topic/meeting name] including: attendees, agenda, decisions, and action items.",
    required_integrations: ["docs"],
    optional_integrations: ["calendar", "slack"],
  },
  {
    id: "weekly_summary",
    title: "Weekly summary",
    description: "Inbox, calendar, and tasks",
    base_prompt: "Give me a weekly summary: unread email count, calendar events this week, and any overdue tasks (from Linear, Jira, or Asana).",
    required_integrations: [],
    optional_integrations: ["gmail", "calendar", "linear", "jira", "asana"],
  },
  {
    id: "invoice_reminder",
    title: "Invoice follow-up",
    description: "Stripe invoices to chase",
    base_prompt: "List Stripe invoices that are past due or unpaid, and draft a short follow-up email for each.",
    required_integrations: ["stripe"],
    optional_integrations: ["gmail"],
  },
  {
    id: "social_post",
    title: "Post to social media",
    description: "Share on Bluesky or X",
    base_prompt: "Post this to [Bluesky / X / both]: [your message].",
    required_integrations: [],
    optional_integrations: ["bluesky", "twitter"],
  },
  {
    id: "feedback_to_linear",
    title: "Turn feedback into Linear issue",
    description: "Create issue from user feedback",
    base_prompt: "Create a Linear issue from this user feedback: [paste feedback]. Set appropriate labels and priority.",
    required_integrations: ["linear"],
    optional_integrations: ["slack", "gmail"],
  },
  {
    id: "slides_outline",
    title: "Draft presentation outline",
    description: "Create slides structure",
    base_prompt: "Create a Google Slides presentation with outline for [topic]: title slide, main points, and summary.",
    required_integrations: ["slides"],
    optional_integrations: [],
  },
  {
    id: "todo_from_email",
    title: "Todo from email",
    description: "Extract action items",
    base_prompt: "Read my most recent unread emails and create a todo list of action items with due dates.",
    required_integrations: ["gmail"],
    optional_integrations: ["notion", "linear"],
  },
  {
    id: "facebook_page_post",
    title: "Post to Facebook page",
    description: "Share on your page",
    base_prompt: "Post to my Facebook page: [your message].",
    required_integrations: ["facebook"],
    optional_integrations: [],
  },
  {
    id: "zendesk_reply",
    title: "Draft Zendesk reply",
    description: "Reply to a ticket",
    base_prompt: "Draft a reply to Zendesk ticket [id] addressing the customer's issue.",
    required_integrations: ["zendesk"],
    optional_integrations: [],
  },
];
