import type { AgentModel } from "@/lib/api";

export const STATIC_MODELS: Record<string, AgentModel[]> = {
  openai: [
    { id: "gpt-4o-mini", name: "GPT-4o mini" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "gpt-5-mini", name: "GPT-5 mini" },
    { id: "gpt-5-nano", name: "GPT-5 nano" },
    { id: "gpt-5.2-pro", name: "GPT-5.2 Pro" },
    { id: "gpt-4.1", name: "GPT-4.1" },
  ],
  openrouter: [],
  claude: [
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
  ],
  gemini: [
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro (preview)" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash (preview)" },
  ],
  ollama: [
    { id: "qwen3.5:27b", name: "Qwen 3.5 27B" },
    { id: "qwen3.5:35b", name: "Qwen 3.5 35B" },
    { id: "qwen3.5:122b", name: "Qwen 3.5 122B" },
    { id: "glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "qwen3-vl:8b", name: "Qwen3-VL 8B" },
    { id: "qwen3-vl:30b", name: "Qwen3-VL 30B" },
    { id: "qwen3-vl:32b", name: "Qwen3-VL 32B" },
    { id: "qwen3-next:80b", name: "Qwen3-Next 80B" },
    { id: "nemotron-3-nano:30b", name: "Nemotron 3 Nano 30B" },
    { id: "gpt-oss-safeguard:20b", name: "GPT-OSS Safeguard 20B" },
    { id: "gpt-oss-safeguard:120b", name: "GPT-OSS Safeguard 120B" },
    { id: "qwen3:8b", name: "Qwen 3 8B" },
    { id: "qwen3:14b", name: "Qwen 3 14B" },
    { id: "qwen3:30b", name: "Qwen 3 30B" },
    { id: "qwen3:32b", name: "Qwen 3 32B" },
    { id: "qwen3:235b", name: "Qwen 3 235B" },
    { id: "gpt-oss:20b", name: "GPT-OSS 20B" },
    { id: "gpt-oss:120b", name: "GPT-OSS 120B" },
    { id: "magistral:24b", name: "Magistral 24B" },
    { id: "deepseek-v3.1:671b", name: "DeepSeek V3.1 671B" },
    { id: "deepseek-r1:7b", name: "DeepSeek R1 7B" },
    { id: "deepseek-r1:8b", name: "DeepSeek R1 8B" },
    { id: "deepseek-r1:14b", name: "DeepSeek R1 14B" },
    { id: "deepseek-r1:32b", name: "DeepSeek R1 32B" },
    { id: "deepseek-r1:70b", name: "DeepSeek R1 70B" },
    { id: "deepseek-r1:671b", name: "DeepSeek R1 671B" },
    { id: "llama3.2:3b", name: "Llama 3.2 3B" },
    { id: "llama3.1:8b", name: "Llama 3.1 8B" },
    { id: "llama3.1:70b", name: "Llama 3.1 70B" },
    { id: "hermes3:8b", name: "Hermes 3 8B" },
    { id: "hermes3:70b", name: "Hermes 3 70B" },
    { id: "mistral", name: "Mistral 7B" },
    { id: "gemma2:9b", name: "Gemma 2 9B" },
    { id: "qwen2:7b", name: "Qwen 2 7B" },
    { id: "qwen2:72b", name: "Qwen 2 72B" },
  ],
};
